ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'python'
2020-09-03 11:06:08.785601: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/openmind/cudnn/cudnn-8.0-v5.1/lib64:/cm/shared/openmind/cuda/8.0/lib64:/cm/shared/openmind/cuda/8.0/lib
2020-09-03 11:06:08.785870: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/openmind/cudnn/cudnn-8.0-v5.1/lib64:/cm/shared/openmind/cuda/8.0/lib64:/cm/shared/openmind/cuda/8.0/lib
2020-09-03 11:06:08.785896: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-09-03 11:06:14.497296: W tensorflow/python/util/util.cc:319] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2020-09-03 11:06:14.670686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-03 11:06:14.675668: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-09-03 11:06:14.675712: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: node091
2020-09-03 11:06:14.675723: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: node091
2020-09-03 11:06:14.675829: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.82.0
2020-09-03 11:06:14.675871: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.82.0
2020-09-03 11:06:14.675881: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.82.0
2020-09-03 11:06:14.676276: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-09-03 11:06:14.700159: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2020-09-03 11:06:14.701371: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564c3a167150 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-03 11:06:14.701433: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
All model checkpoint weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.
All model checkpoint weights were used when initializing TFTransfoXLLMHeadModel.

All the weights of TFTransfoXLLMHeadModel were initialized from the model checkpoint at transfo-xl-wt103.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use TFTransfoXLLMHeadModel for predictions without further training.
Old sentence is:  ["So he 's going to have to start looking for another place ."]  with JS:  0.3719903230667114
['RON']
['Les']
['Name']
['Name']
['team']
['Sur']
['Mut']
['Wa']
['Code']
['Boss']
New sentence is:  Boss  with JS: 0.49279463291168213
2 10
Traceback (most recent call last):
  File "judge_sentences.py", line 150, in <module>
    replace_words(model_info, sent, joint_vocab, 10)
  File "judge_sentences.py", line 118, in replace_words
    plt.plot(range(0,len(scores)), scores)
NameError: name 'plt' is not defined
